id: daily_cybersecurity_news
namespace: homelab

description: |
  Daily automated cybersecurity intelligence briefing that uses the cybersecurity news agent
  to fetch RSS feeds, analyze and categorize content, and generates a structured markdown report.
  The agent container includes built-in RSS fetching and analysis capabilities.
  This flow uses modular subflows for maximum reusability.

triggers:
  - id: daily_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 7 * * *"  # Run daily at 7 AM

tasks:
  - id: analyze_content
    type: io.kestra.plugin.core.flow.Subflow
    namespace: subflows
    flowId: claude_content_analyzer
    inputs:
      analysis_type: "daily"
    description: Use cybersecurity news agent to fetch RSS feeds and analyze content

  - id: generate_report
    type: io.kestra.plugin.core.flow.Subflow
    namespace: subflows
    flowId: markdown_report_generator
    inputs:
      analyzed_content: "{{ outputs.analyze_content.outputs.analyzed_content }}"
      report_type: "daily"
      report_date: "{{ execution.startDate | date('yyyy-MM-dd') }}"
    description: Generate formatted markdown briefing report

  - id: display_report
    type: io.kestra.plugin.core.log.Log
    message: |
      ============================================
      CYBERSECURITY BRIEFING REPORT
      ============================================

      {{ read(outputs.generate_report.outputs.report_file) }}

      ============================================
      END OF REPORT
      ============================================

  - id: log_summary
    type: io.kestra.plugin.core.log.Log
    message: |
      ✅ Cybersecurity briefing complete!

      📄 VIEW REPORT: See "display_report" task logs above for full content

      📥 DOWNLOAD OPTIONS:

      Internal URI (for API/CLI):
      {{ outputs.generate_report.outputs.report_file }}

      Download via Kestra CLI:
      kestra outputs download "{{ outputs.generate_report.outputs.report_file }}"

      📊 STATISTICS:
      - Total Articles: {{ outputs.analyze_content.outputs.analyzed_content | jq('.metadata.total_articles') }}
      - Analyzed Count: {{ outputs.analyze_content.outputs.analyzed_content | jq('.metadata.analyzed_count') }}
      - Timestamp: {{ outputs.analyze_content.outputs.analyzed_content | jq('.metadata.timestamp') }}
