id: daily_cybersecurity_news
namespace: homelab

description: |
  Daily automated cybersecurity intelligence briefing that monitors curated RSS feeds,
  uses Claude AI to analyze and categorize content, and generates a structured markdown report.
  This flow uses modular subflows for maximum reusability.

triggers:
  - id: daily_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 7 * * *"  # Run daily at 7 AM

inputs:
  - id: hours_back
    type: INT
    description: "Hours of news to collect (default: 24)"
    defaults: 24

tasks:
  - id: collect_feeds
    type: io.kestra.plugin.core.flow.Subflow
    namespace: subflows
    flowId: rss_feed_collector
    inputs:
      hours_back: "{{ inputs.hours_back }}"
    description: Fetch and parse RSS feeds from curated cybersecurity sources

  - id: analyze_content
    type: io.kestra.plugin.core.flow.Subflow
    namespace: subflows
    flowId: claude_content_analyzer
    inputs:
      content_data: "{{ outputs.collect_feeds.outputs.feeds_data }}"
      analysis_type: "daily"
    description: Use Claude AI to analyze, categorize, and filter content

  - id: generate_report
    type: io.kestra.plugin.core.flow.Subflow
    namespace: subflows
    flowId: markdown_report_generator
    inputs:
      analyzed_content: "{{ outputs.analyze_content.outputs.analyzed_content }}"
      report_type: "daily"
      report_date: "{{ execution.startDate | date('yyyy-MM-dd') }}"
      feed_status: "{{ outputs.collect_feeds.outputs.feeds_data | jq('.feed_status') }}"
    description: Generate formatted markdown briefing report

  - id: save_report
    type: io.kestra.plugin.core.storage.LocalFiles
    description: Save report to namespace files for historical reference
    inputs:
      briefing.md: "{{ outputs.generate_report.outputs.report_file }}"

  - id: display_report
    type: io.kestra.plugin.core.log.Log
    message: |
      ============================================
      CYBERSECURITY BRIEFING REPORT
      ============================================

      {{ read(outputs.generate_report.outputs.report_file) }}

      ============================================
      END OF REPORT
      ============================================

  - id: log_summary
    type: io.kestra.plugin.core.log.Log
    message: |
      ✅ Cybersecurity briefing complete!

      📄 VIEW REPORT: See "display_report" task logs above for full content

      📥 DOWNLOAD OPTIONS:

      Internal URI (for API/CLI):
      {{ outputs.generate_report.outputs.report_file }}

      Download via Kestra CLI:
      kestra outputs download "{{ outputs.generate_report.outputs.report_file }}"

      📊 STATISTICS:
      - Total Articles: {{ outputs.collect_feeds.outputs.feeds_data | jq('.total_articles') }}
      - Time Range: {{ outputs.collect_feeds.outputs.feeds_data | jq('.time_range.from') }} to {{ outputs.collect_feeds.outputs.feeds_data | jq('.time_range.to') }}
