id: weekly_cybersecurity_summary
namespace: homelab

description: |
  Weekly cybersecurity intelligence summary that aggregates the past 7 daily briefings,
  identifies trends, recurring threats, and generates a comprehensive weekly overview.
  Runs every Monday morning after the daily briefing completes.

triggers:
  - id: weekly_schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 8 * * 1"  # Run at 8 AM every Monday (1 hour after daily briefing)

tasks:
  - id: fetch_daily_reports
    type: io.kestra.plugin.scripts.python.Script
    description: Load last 7 daily briefing files from namespace storage
    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      image: python:3.11-slim
    beforeCommands:
      - pip install requests
    outputFiles:
      - "weekly_data.json"
    script: |
      import json
      from datetime import datetime, timedelta
      import os

      # Calculate the date range for the past 7 days (including today)
      end_date = datetime.now()
      date_range = []
      reports = []

      for i in range(7):
          date = end_date - timedelta(days=i)
          date_str = date.strftime('%Y-%m-%d')
          date_range.append(date_str)

      date_range.reverse()  # Oldest to newest

      print(f"Looking for daily reports from: {date_range[0]} to {date_range[-1]}")

      # In a real implementation, you would fetch these from Kestra namespace storage
      # For now, we'll create a structure that expects the reports to be available
      # This is a placeholder that will need to be adapted based on actual namespace file access

      # TODO: Update this to actually fetch from namespace storage using Kestra's file access
      # For now, create a structure that the analyzer can work with

      weekly_data = {
          "date_range": {
              "start": date_range[0],
              "end": date_range[-1]
          },
          "reports": [],
          "metadata": {
              "expected_reports": 7,
              "found_reports": 0,
              "missing_dates": []
          }
      }

      # Note: In production, this would iterate through namespace files
      # and load each daily briefing markdown file
      for date_str in date_range:
          # Placeholder for actual namespace file retrieval
          # In Kestra, you would use something like:
          # file_uri = f"kestra:///io/kestra/storage/homelab/briefings/briefing-{date_str}.md"
          # report_content = read_from_storage(file_uri)

          report_entry = {
              "date": date_str,
              "filename": f"briefing-{date_str}.md",
              "status": "placeholder",
              "content": f"Placeholder for report from {date_str}"
          }

          weekly_data["reports"].append(report_entry)
          weekly_data["metadata"]["missing_dates"].append(date_str)

      print(f"\nWeekly data structure created")
      print(f"Date range: {weekly_data['date_range']}")
      print(f"Reports to analyze: {len(weekly_data['reports'])}")

      with open('weekly_data.json', 'w') as f:
          json.dump(weekly_data, f, indent=2)

      print("\n📊 Weekly data collection complete")

  - id: aggregate_analysis
    type: io.kestra.plugin.core.flow.Subflow
    namespace: subflows
    flowId: claude_content_analyzer
    inputs:
      content_data: "{{ outputs.fetch_daily_reports.outputs.weekly_data }}"
      analysis_type: "weekly"
    description: Use Claude AI to aggregate and analyze weekly trends

  - id: generate_weekly_report
    type: io.kestra.plugin.core.flow.Subflow
    namespace: subflows
    flowId: markdown_report_generator
    inputs:
      analyzed_content: "{{ outputs.aggregate_analysis.outputs.analyzed_content }}"
      report_type: "weekly"
      report_date: "{{ execution.startDate | date('yyyy-MM-dd') }}"
    description: Generate formatted weekly summary markdown report

  - id: display_weekly_report
    type: io.kestra.plugin.core.log.Log
    message: |
      ============================================
      WEEKLY CYBERSECURITY SUMMARY
      ============================================

      {{ read(outputs.generate_weekly_report.outputs.report_file) }}

      ============================================
      END OF WEEKLY SUMMARY
      ============================================

  - id: log_summary
    type: io.kestra.plugin.core.log.Log
    message: |
      ✅ Weekly cybersecurity summary complete!

      📄 VIEW REPORT: See "display_weekly_report" task logs above for full content

      📥 DOWNLOAD OPTIONS:

      Internal URI (for API/CLI):
      {{ outputs.generate_weekly_report.outputs.report_file }}

      Download via Kestra CLI:
      kestra outputs download "{{ outputs.generate_weekly_report.outputs.report_file }}"

      📊 SUMMARY:
      - Reports Analyzed: 7 daily briefings
      - Week Ending: {{ execution.startDate | date('yyyy-MM-dd') }}
